/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog_cafe_g1;

import java.util.Arrays;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author fshaik
 */
public class Prog_Cafe_Order_Form extends javax.swing.JFrame {

    /**
     * Creates new form Prog_Cafe_Order_Form
     */
    public Prog_Cafe_Order_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        mainIngredient_Label = new javax.swing.JLabel();
        mainIngredients_ComboBox = new javax.swing.JComboBox<>();
        bread_Label = new javax.swing.JLabel();
        bread_ComboBox = new javax.swing.JComboBox<>();
        toppings_Label = new javax.swing.JLabel();
        lettuce_CheckBox = new javax.swing.JCheckBox();
        cheese_CheckBox = new javax.swing.JCheckBox();
        onions_CheckBox3 = new javax.swing.JCheckBox();
        bellPeppers_CheckBox = new javax.swing.JCheckBox();
        tomato_CheckBox = new javax.swing.JCheckBox();
        toastedChoice_Label = new javax.swing.JLabel();
        toasted_RadioButton = new javax.swing.JRadioButton();
        nonToasted_RadioButton = new javax.swing.JRadioButton();
        specialInstructions_Label = new javax.swing.JLabel();
        specialInstructions_ScrollPane = new javax.swing.JScrollPane();
        specialInstructions_TextArea = new javax.swing.JTextArea();
        summary_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        summary_List = new javax.swing.JList<>();
        order_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(51, 102, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Prog Cafe - Sandwich Order");
        title.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 102), 1, true));

        mainIngredient_Label.setText("Main Ingredient:");

        mainIngredients_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chicken", "Beef", "Tuna", "Veggie Patty", "Mutton" }));

        bread_Label.setText("Bread Choices:");

        bread_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White Bread", "Whole-Wheat Bread", "Italian Bread", "Rye Bread", "Gluten-Free Bread" }));

        toppings_Label.setText("Toppings:");

        lettuce_CheckBox.setText("Lettuce");

        cheese_CheckBox.setText("Cheese");

        onions_CheckBox3.setText("Onions");

        bellPeppers_CheckBox.setText("Bell Peppers");

        tomato_CheckBox.setText("Tomato");

        toastedChoice_Label.setText("Toasted Choice:");

        buttonGroup1.add(toasted_RadioButton);
        toasted_RadioButton.setText("Toasted");

        buttonGroup1.add(nonToasted_RadioButton);
        nonToasted_RadioButton.setText("Non-Toasted");

        specialInstructions_Label.setText("Special Instructions:");

        specialInstructions_TextArea.setColumns(20);
        specialInstructions_TextArea.setRows(5);
        specialInstructions_ScrollPane.setViewportView(specialInstructions_TextArea);

        summary_Label.setText("Order Summary:");

        jScrollPane1.setViewportView(summary_List);

        order_Button.setText("Show Order Summary");
        order_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainIngredient_Label)
                                .addGap(18, 18, 18)
                                .addComponent(mainIngredients_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157)
                                .addComponent(bread_Label)
                                .addGap(18, 18, 18)
                                .addComponent(bread_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toastedChoice_Label)
                                .addGap(18, 18, 18)
                                .addComponent(toasted_RadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(nonToasted_RadioButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(toppings_Label)
                                    .addGap(18, 18, 18)
                                    .addComponent(lettuce_CheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(cheese_CheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(onions_CheckBox3)
                                    .addGap(18, 18, 18)
                                    .addComponent(bellPeppers_CheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(tomato_CheckBox))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(specialInstructions_Label)
                                        .addComponent(summary_Label))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(specialInstructions_ScrollPane)
                                        .addComponent(jScrollPane1)))))))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(order_Button)
                .addGap(347, 347, 347))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainIngredient_Label)
                    .addComponent(mainIngredients_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bread_Label)
                    .addComponent(bread_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toppings_Label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lettuce_CheckBox)
                        .addComponent(cheese_CheckBox)
                        .addComponent(onions_CheckBox3)
                        .addComponent(bellPeppers_CheckBox)
                        .addComponent(tomato_CheckBox)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toastedChoice_Label)
                    .addComponent(toasted_RadioButton)
                    .addComponent(nonToasted_RadioButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(specialInstructions_Label))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(specialInstructions_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(summary_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(order_Button)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void order_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_ButtonActionPerformed
        //Create a String Builder for the order summary
        StringBuilder orderSummary = new StringBuilder();
        //Get the selected main ingredient from the combo-box
        orderSummary.append("Main Ingredient: ").append(mainIngredients_ComboBox.getSelectedItem()).append("\n");
        //Get the selected bread choice from the order summary
        orderSummary.append("Bread Choice:").append(bread_ComboBox.getSelectedItem()).append("\n");
        //Toppings selection using an array of checkboxes & its corresponding names
        JCheckBox [] checkboxes = {lettuce_CheckBox,cheese_CheckBox,onions_CheckBox3,bellPeppers_CheckBox,tomato_CheckBox};
        String [] toppingsNames = {"Lettuce", "Cheese", "Onions", "Bell Peppers", "Tomato"};
        
        StringBuilder toppings = new StringBuilder("Toppings: ");
        for(int i = 0; i < checkboxes.length; i++){
                if(checkboxes[i].isSelected()){
                            toppings.append(toppingsNames[i]).append(" , ");
                }
        }
        //Remove trailing comma & space, if present
        if(toppings.charAt(toppings.length() -2) == ','){
                toppings.delete(toppings.length() -2 , toppings.length());
    }
        toppings.append("\n");
        //Append to the toppings to the main summary
        orderSummary.append(toppings);
        
        //Get toasted choice
        if(toasted_RadioButton.isSelected()){
                orderSummary.append("Toasted Choice: Toasted\n");
        } else if(nonToasted_RadioButton.isSelected()){
            orderSummary.append("Toasted Choice: Non-Toasted\n");
        }
        
        //Get the special instrustions if any
        if(!specialInstructions_TextArea.getText().trim().isEmpty()){
                orderSummary.append("Special Instructions: ").append(specialInstructions_TextArea.getText().trim()).append("\n");
        }
        
        //Convert the StringBuilder to a List of Strings, with each string as a line item
        List<String> lines = null;
        lines = Arrays.asList(orderSummary.toString().split("\n"));
        summary_List.setListData(lines.toArray(new String[0]));
    }//GEN-LAST:event_order_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prog_Cafe_Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prog_Cafe_Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prog_Cafe_Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prog_Cafe_Order_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prog_Cafe_Order_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bellPeppers_CheckBox;
    private javax.swing.JComboBox<String> bread_ComboBox;
    private javax.swing.JLabel bread_Label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cheese_CheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lettuce_CheckBox;
    private javax.swing.JLabel mainIngredient_Label;
    private javax.swing.JComboBox<String> mainIngredients_ComboBox;
    private javax.swing.JRadioButton nonToasted_RadioButton;
    private javax.swing.JCheckBox onions_CheckBox3;
    private javax.swing.JButton order_Button;
    private javax.swing.JLabel specialInstructions_Label;
    private javax.swing.JScrollPane specialInstructions_ScrollPane;
    private javax.swing.JTextArea specialInstructions_TextArea;
    private javax.swing.JLabel summary_Label;
    private javax.swing.JList<String> summary_List;
    private javax.swing.JLabel title;
    private javax.swing.JLabel toastedChoice_Label;
    private javax.swing.JRadioButton toasted_RadioButton;
    private javax.swing.JCheckBox tomato_CheckBox;
    private javax.swing.JLabel toppings_Label;
    // End of variables declaration//GEN-END:variables
}
